### ISSUE TITLE
Development To-Do

### ISSUE THREAD

**Issue by twizmwazin** [CardinalDevelopment/Meta#1]
This is my proposed order to get off the ground.
1. Cardinal Plugin
2. [ ] Establish and document a protocol for maps.
3. [ ] Create a test suite of maps to develop the plugin against. This means create maps that conform to the documented protocol. Ideally, these maps can also be used for the end product. These should be designed to test as many protocol features as possible, including corner-cases.
4. [ ] Implement modules to support the maps created.
5. [ ] Implement a pseudo-API to allow other plugins to interact.
6. Database
7. [ ] Establish and document all data that needs to be stored from Minecraft.
8. [ ] Establish and document schema to be used to store established data from Minecraft.
9. [ ] Establish and document all data that needs to be stored from the Website.
10. [ ] Establish and document schema to be used to store established data from Website.
11. Database Integration Plugin
12. [ ] For each data type to be stored in the database, implement a means of recording and storing the data in the database.
13. Bungee Plugin (TBD)
14. [ ] Determine requirements for such a plugin.
15. Website
16. [ ] Implement a mean to view player statistics.
17. [ ] Implement a method for players to create a personal profile linked to their in-game account.
18. [ ] Implement a way for players to purchase virtual items from the website.
19. [ ] Implement mean(s) for players to communicate through the website.

Profit??
